import { NextRequest, NextResponse } from "next/server";

export async function POST(request: NextRequest) {
  try {
    const { query } = await request.json();

    if (!query) {
      return NextResponse.json({ error: "Query is required" }, { status: 400 });
    }

    // Simple response for now - you can add AI integration later
    const result = `Legal Research Result for: "${query}"

Based on your query, here are the key legal considerations:

1. **Property Encroachment Laws in India:**
   - The Transfer of Property Act, 1882 governs property rights
   - Section 105 defines lease and property boundaries
   - Encroachment is a civil wrong under tort law

2. **Legal Remedies Available:**
   - File a civil suit for possession under Order 39 Rule 1 of CPC
   - Seek injunction to prevent further encroachment
   - Claim damages for any loss suffered
   - Approach local authorities for removal of encroachment

3. **Steps to Take:**
   - Document the encroachment with photos/videos
   - Send legal notice to the encroacher
   - File complaint with local police if needed
   - Consult a property lawyer for specific advice

4. **Important Considerations:**
   - Preserve all evidence of encroachment
   - Act within limitation period (3 years for civil suits)
   - Consider mediation before litigation
   - Check property documents and boundaries

Note: This is general legal information. Please consult a qualified lawyer for specific advice on your case.

---
Generated by LegalIndia.ai - Simple Research Tool`;

    return NextResponse.json({ result });

  } catch (error) {
    console.error("Research error:", error);
    return NextResponse.json({ error: "Research failed" }, { status: 500 });
  }
}
